name: dnstt_xyz_app
description: "DNSTT Client - DNS Tunnel Mobile App"
publish_to: 'none'

version: 2.2.0+5

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.5
  path_provider: ^2.1.5
  http: ^1.3.0
  uuid: ^4.5.1
  url_launcher: ^6.2.5
  ffi: ^2.1.3
  file_picker: ^8.0.0
  share_plus: ^10.0.0
  socks5_proxy: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/dns/
